gText_SetClock_WokeMeUp::
	.string "………………………………………………\n"
	.string "………………………………………………\p"
	.string "Zzz… Hm? Quoi…?\n"
	.string "Tu m'a réveillé!\p"
	.string "Mais quelle heure est-il?$"

gText_Oak_Welcome:: @ 82C897B
	.string "Bonjour! Désolé de l'attente!\p"
	.string "Bienvenue dans le monde de\n{POKEMON}!\p"
	.string "Mon nom est CHEN.\p"
	.string "Mais on m'appelle le PROF. {POKEMON}.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Ce monde…$"

gText_Oak_Pokemon2::
	.string "…est peuplé de créatures\n"
	.string "appelées {POKEMON}.\p"
	.string "$"

gText_Oak_MainSpeech::
	.string "Humains et {POKEMON} vivent en parfaite\n"
	.string "harmonie...\p"
	.string "Certains jouent avec les {POKEMON},\n"
	.string "d'autres font des combats avec eux.\p"
	.string "$"

gText_Oak_MainSpeech2::
	.string "Mais il reste beaucoup à apprendre\n"
	.string "sur nos amis les {POKEMON}.\p"
	.string "De nombreux mystères planent à\n leur sujet.\p"
	.string "Et c'est pourquoi j'etudie les {POKEMON}\n"
	.string "tous les jours.\p"
	.string "Euh...C'est quoi ton nom?\n"
	.string "Assez parlé de moi.\n"
	.string "Parle moi un peu de toi.\p"
	.string "$"

gText_Oak_BoyOrGirl::
	.string "Es-tu un garcon?\n"
	.string "Ou une fille?$"

gText_Oak_WhatsYourName::
    .string "Heu...C'est quoi ton nom?\p"
	.string "$"

gText_Oak_SoItsPlayer::
	.string "D'accord…\n"
	.string "Donc ton nom est {PLAYER}.$"

gText_Oak_AreYouReady::
	.string "{PLAYER}, tu es prêt?\p"
	.string "Ta quete est sur le point de\ncommencer.\p"
	.string "Joies et périls paveront ta route...\p"
	.string "Un monde de revem de dangers et de\n"
	.string "{POKEMON} t'attend! En avant!\p"
	.string "Un monde de rêve, de dangers et de\n"
	.string "{POKEMON} t'attend! En avant!\p"
	.string "À plus tard!$"
