	.align 2
gText_ConfirmSave::
	.string "Voulez-vous sauvegarder la partie?$"

gText_AlreadySavedFile::
	.string "Il y a déjà une sauvegarde.\n"
	.string "La remplacer?$"

gText_SavingDontTurnOff::
	.string "SAUVEGARDE…\n"
	.string "NE PAS ETEINDRE.$"

gText_PlayerSavedGame::
	.string "{PLAYER} a sauvegardé la partie.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "{POKEMON}, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "SAUVEGARDE…\n"
	.string "NE PAS ETEINDRE.$.$"
